title: "bash-board"
description: "Board Jekyll blog theme."
author:
  name: "vllur"
  
url: "https://vllur.github.io"
baseurl: /bash-board

source: .
destination: ./_site
permalink: /:title
paginate: 4
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

sass:
    style: compressed
future: true
exclude: [vendor]
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

google_analytics: ""
owner: "vllur"
lang: "en_GB"
iso-lang: "en"